name: Django CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # 최신 Python 버전 사용

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r workwise-01/backend/requirements.txt  # requirements.txt 경로

      - name: Run Django tests with coverage
        env:
          DJANGO_SETTINGS_MODULE: backend.settings  # Django settings 경로
        run: |
          cd workwise-01/backend  # Django 프로젝트 디렉토리로 이동
          coverage run manage.py test
          coverage xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: workwise-01/backend/coverage.xml  # 커버리지 파일 경로
          fail_ci_if_error: true