name: Django CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13  # PostgreSQL 버전 지정
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: asd123
          POSTGRES_DB: workwise_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # 최신 Python 버전 사용

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r workwise-01/backend/requirements.txt
          pip install coverage  # coverage 설치

      - name: Run Django tests with coverage
        env:
          DJANGO_SETTINGS_MODULE: backend.settings
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: asd123
          POSTGRES_DB: workwise_db
          DATABASE_HOST: localhost  # PostgreSQL 호스트 설정
          DATABASE_PORT: 5432
        run: |
          cd workwise-01/backend
          coverage run manage.py test
          coverage report